### ISSUE TITLE
Gehirnsturm 04.nov

### ISSUE THREAD

**Issue by Nano1237** [Hanover-Game-Off-Community/game-off-nov-2019#1]
- Über boundaries leapen
- genre grenzen durchbrechen
- spielgrenzen durchbrechen (z.b. wenn du stirbs fängt das spiel erst richtig an)
- wenn man stirbt kommt man zum endboss und wenn du da stirbst kommst du wieder ins leben wo du leveln kannst um den endboss zu besiegen.
- story könnte z.b ein albtraum sein
- powerups für castlevania mäßig um einfache level beim sterben wieder überspringen zu können
- gegner spwanen wieder neu wenn du ein level betrittst
- der boss levelt auch, wenn du stirbst
- boss kommt dir entgegen und wird auch leveln -> du musst so schnell wie möglich gegner killen um seine gegner schneller zu killen
- prozedual generierte map
_____________________

- 2D Plattformer (frontal ansicht)
- Pixelart style
- Hauptspielmechanik ist es gegen einen Boss zu spielen, der dir entgegen kommt und mit strecke levelt (er rettet die mobs die du killen könntest)
- durch schnelles bewegen kann man auch leveln (z.b. "selen" sammeln die nach einer gewissen zeit verschwinden)
- albtraum thema
- wir sind ein dämon und der boss ist der eigentliche held im spiel
- der eigentliche endboss (engel) ist der, der dir beim sterben erscheint. der muss ziemlich op sein
- zuerst spielt man den helden, welcher nach links läuft. dann stirbt man und wird der dämon und kämpft gegen den helden
- mit dem helden spielt man nur das tutorial um die spielmechanik zu verstehen
- wechsel von held zu dämon musikalisch abbilden
- besseren loot und bessere gegner durch öfteres spielen der level

- eine schwere die energie verbraucht und eine leichte attacke
- blocken ist auch mit energieverbrauch möglich

auch gegner blocken, wenn sie schilde haben

level 1 (wald -> tiere sind gegner und der geist des waldes ist der boss)
level 2 (felder mit vereinzelten dörfern -> bauern sind gegner der boss ist der held des dorfes) (ende ist stadtmauer und der boss ist)
level 3 (in der stadt -> gegner sind soldaten und der boss ist der kommandant)
level 4 (in der kathedrale -> kreuzritter sind die gegner  man bekommt aber permamnent schaden durch den aufenthalt in der kirche (brennen)) -> geiler loot durch starke gegner
______________________

**Comment by kev1896** [comment]
Den Wald sollten wir aufgrund fehlender Zeit streichen, bzw. das Tutorial im Wald spielen lassen.
